//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by romdbLauncher.rc
//
#define IDC_MYICON 2
#define IDD_ROMDBLAUNCHER_DIALOG 102
#define IDS_APP_TITLE 103
#define IDD_ABOUTBOX 103
#define IDM_ABOUT 104
#define IDM_EXIT 105
#define IDI_ROMDBLAUNCHER 107
#define IDI_SMALL 108
#define IDC_ROMDBLAUNCHER 109
#define IDR_MAINFRAME 128
#define ID_SEARCHBOX 1200
#define ID_SEARCHBTN 1201
#define ID_SEARCHRESULTS 1202
#define ID_SEARCHROM 1203
#define ID_OPENROM 1204
#define IDM_OPENCONFIGURATIONFILE 2000
#define IDM_RELOADCONFIGURATION 2001
#define IDM_DELETEFILEONCLOSE 2002
#define IDM_INCLUDEMEDIAINSEARCH 2003
#define IDM_ALLSYSTEMS 2004
#define IDC_STATIC -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC 1
#define _APS_NEXT_RESOURCE_VALUE 129
#define _APS_NEXT_COMMAND_VALUE 2005
#define _APS_NEXT_CONTROL_VALUE 1000
#define _APS_NEXT_SYMED_VALUE 110
#endif
#endif
